# GoReleaser configuration for SQLBuddy
project_name: sqlbuddy

before:
  hooks:
    - go mod tidy

builds:
  - skip: true  # Skip binary builds as this is a library

changelog:
  use: github-native

checksum:
  name_template: 'checksums.txt'

release:
  github:
    # no need to specify repository in github
  prerelease: auto
  draft: false
  name_template: "SQLBuddy v{{.Version}}"
  extra_files:
    - glob: ./Changelog.md